---
title: Harware and Algorithm Flowchart
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: LINEAR_SEGMENTS
---

flowchart
%%Analog in
    A0[[A0]]
    %%A1[[A1]]
    %%A2[[A2]]
    %%A3[[A3]]
    %%A4[[A4]]
    %%A5[[A5]]
%%Digital in
    %%D1((D1))
    %%D2((D2))
    D3((D3))
    D4((D4))
    D5((D5))
    %%D6((D6))
    %%D7((D7))
    %%D8((D8))
    %%D9((D9))
    %%D10((D10))
    %%D11((D11))
    %%D12((D12))
    SDA[SDA]
    SCL[SCL]
MCU@{shape: card ,label: "Arduino UNO\ncontroller"}
HWMIN@{shape: event ,label: "MIN level sensor"}
HWMAX@{shape: event ,label: "MAX level sensor"}
HWSD@{shape: disk ,label: "SD card"}
HWFLOW@{shape: ,label: "Flowmeter pulses"}
HWPH@{shape: ,label: "pH sensor analog"}
HWRTC@{shape: ,label: "RTC time"}
I2C@{shape: ,label: "I2C HUB"}
HWRELAY@{shape: ,label: "Relay module"}
HWVALVE@{shape: ,label: "12V solenoid valve"}
subgraph Hardware
        HWMIN -->|digital| D3
        D3-->|digital| MCU
        HWMAX -->|digital| D4
        D4 -->|digital| MCU
        HWFLOW -->|interrupt| D5
        D5 -->|interrupt| MCU
        HWPH -->|analog| A0
        A0 -->|analog| MCU
        HWRTC -->|I2C|I2C
        HWSD -->|I2C| I2C
        
        MCU -->|control| HWRELAY
        HWRELAY -->|switch 12V| HWVALVE
        I2C --> SDA
        I2C --> SCL
        SDA --> MCU
        SCL --> MCU
    end

Strat((Start))
LG1@{shape: ,label: "MIN level sensor triggered"}
style Strat fill:#0f0,stroke:#050,stroke-width:4px
LGQ1@{shape: diam ,label: "MAX level sensor triggered?"}
LG2@{shape: ,label: "Read START_TS"}
LG3@{shape: ,label: "Open valve"}
LG4@{shape: ,label: "Count pulses"}
LGQ2@{shape: diam ,label: "Timeout"}
LGX@{shape:  ,label: "Close valve TIMEOUT"}
LG5@{shape:  ,label: "Close valve OK"}
LG6@{shape:  ,label: "Compute volume"}
LG8@{shape:  ,label: "Write CSV to SD"}
subgraph Algorithm
        Strat --> LG1
        LG1 --> LG2
        LG2 --> LG3
        LG3 --> LG4
        LG4 --> LGQ1
        LGQ1 -- No --> LGQ2
        LGQ2 -- No --> LGQ1 
        LGQ2 -- Yes --> LGX
        LGQ1-- Yes --> LG5
        LG5 --> LG6
        LGX --> LG6
    
        LG6 --> LG8
        LG8 -..-> HWSD 

    end
classDef big font-size:30px;
LG7@{shape: curv-trap ,label: "Life_Control pH"}
    class LG7 big;
    LG7 --> MCU